### ISSUE TITLE
HTTPError Message

### ISSUE THREAD

**Issue by DigiTecK3D** [beeb/pancaketrade#12]
Hello, so I've been using this for a time and I get this over a long period of time and usage. not exactly sure what causes it or why it occurs but I do know it's something that shows up after a long time of running the bot. 

`2021-07-18 04:35:47  ERROR  |Exception during message update: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2021-07-18 06:54:37  ERROR  |Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2021-07-18 06:54:37  ERROR  |Exception while handling an update
2021-07-18 06:54:37  ERROR  |urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2021-07-18 06:54:37  ERROR  |An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "C:\Users\migue\Documents\GitHub\pancaketrade\.venv\lib\site-packages\telegram\ext\dispatcher.py", line 536, in process_update
    self.dispatch_error(None, update)
  File "C:\Users\migue\Documents\GitHub\pancaketrade\.venv\lib\site-packages\telegram\ext\dispatcher.py", line 810, in dispatch_error
    callback(update, context)
  File "C:\Users\migue\Documents\GitHub\pancaketrade\pancaketrade\bot.py", line 407, in error_handler
    chat_message(update, context, text=f'⛔️ Exception while handling an update\n{context.error}', edit=False)
  File "C:\Users\migue\Documents\GitHub\pancaketrade\pancaketrade\utils\generic.py", line 74, in chat_message
    assert update.effective_chat
AttributeError: 'NoneType' object has no attribute 'effective_chat'
2021-07-18 06:54:47  ERROR  |Exception during message update: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2021-07-18 06:55:09  ERROR  |Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2021-07-18 06:55:09  ERROR  |Exception while handling an update
2021-07-18 06:55:09  ERROR  |urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2021-07-18 06:55:09  ERROR  |An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "C:\Users\migue\Documents\GitHub\pancaketrade\.venv\lib\site-packages\telegram\ext\dispatcher.py", line 536, in process_update
    self.dispatch_error(None, update)
  File "C:\Users\migue\Documents\GitHub\pancaketrade\.venv\lib\site-packages\telegram\ext\dispatcher.py", line 810, in dispatch_error
    callback(update, context)
  File "C:\Users\migue\Documents\GitHub\pancaketrade\pancaketrade\bot.py", line 407, in error_handler
    chat_message(update, context, text=f'⛔️ Exception while handling an update\n{context.error}', edit=False)
  File "C:\Users\migue\Documents\GitHub\pancaketrade\pancaketrade\utils\generic.py", line 74, in chat_message
    assert update.effective_chat
AttributeError: 'NoneType' object has no attribute 'effective_chat'`

![image](https://user-images.githubusercontent.com/5471872/126076069-e038447a-16b5-4f47-95fd-b16257014f66.png)

**Comment by beeb** [comment]
Hey there. My instance of the bot runs usually weeks without interruption and I never received this error. I think it's a networking error and doesn't constitute a bug in the bot.

**Comment by DigiTecK3D** [comment]
Thank you for the response, it is weird cause at times it doesn't happen and then others it will. But good to know you have run it for a long time without any issues. I'll keep an eye and see if it comes up I can debug it, not really much info to figure out what is going on.

**Comment by YveOms** [comment]
I always run into such problems when serving the bot from my computer. Sometimes my mobile data will switch from 4G to 3G and the above error pops up. When I moved to a VPS server, it can go up to a month without any issues.

**Comment by DigiTecK3D** [comment]
It is something that I'm running from my computer all the time and not on docker or a server so that could be some of the issues going on. I've also been noticing before I get those errors I start getting some of these prior. I will say lately been running for a few days and haven't hit the errors again yet, but it seems a bit random or could be a mobile thing since I do use telegram on my phone to check statuses. 

`2021-08-11 04:55:44 WARNING |Execution of job "TokenWatcher.monitor_price (trigger: interval[0:00:03], next run at: 2021-08-11 04:55:44 CDT)" skipped: maximum number of running instances reached (1)
2021-08-11 04:57:44 WARNING |Execution of job "TokenWatcher.monitor_price (trigger: interval[0:00:03], next run at: 2021-08-11 04:57:44 CDT)" skipped: maximum number of running instances reached (1)`

**Comment by beeb** [comment]
@DigiTecK3D yeah it could be that your computer has a less stable network than a server would in a datacenter. The error message you posted is indicative of that as well. Normally, each token will check its price every 5 seconds (by default) but if the request takes longer than that, it will wait until the previous one is finished a give you this warning. So it means your requests are taking longer than they should.
