### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by scheta1** [beeb/pancaketrade#20]
$ poetry run trade
2021-09-19 05:14:11   INFO  |Bye!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\pancaketrade\trade.py", line 28, in main
    config = read_config(config_file)
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\pancaketrade\utils\config.py", line 88, in read_config
    return parse_config_file(config_file_path)
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\pancaketrade\utils\config.py", line 65, in parse_config_file
    conf['_pk'] = questionary.password(
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\questionary\prompts\password.py", line 59, in password
    return text.text(
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\questionary\prompts\text.py", line 90, in text
    p = PromptSession(
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 468, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 719, in _create_application
    application: Application[_T] = Application(
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\prompt_toolkit\application\application.py", line 277, in __init__
    self.output = output or session.output
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\prompt_toolkit\application\current.py", line 70, in output
    self._output = create_output()
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\prompt_toolkit\output\defaults.py", line 73, in create_output
    return Win32Output(stdout, default_color_depth=color_depth_from_env)
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\prompt_toolkit\output\win32.py", line 107, in __init__
    info = self.get_win32_screen_buffer_info()
  File "C:\Users\Administrator\Downloads\pancaketrade-master\pancaketrade-master\.venv\lib\site-packages\prompt_toolkit\output\win32.py", line 211, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.output.win32.NoConsoleScreenBufferError: Found xterm, while expecting a Windows console. Maybe try to run this program using "winpty" or run it in cmd.exe instead. Or otherwise, in case of Cygwin, use the Python executable that is compiled for Cygwin.

i got this eror

**Comment by beeb** [comment]
As mentioned in the readme this project was not tested on windows. Recommend to use WSL (windows subsystem for Linux) or a Linux server.
