### ISSUE TITLE
Error while running "poetry run trade"

### ISSUE THREAD

**Issue by DjdjHacks** [beeb/pancaketrade#49]
I'm getting this error on running poetry run trade.

2021-11-14 13:50:17   INFO  |Bye!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\HACKER\Desktop\beeb-pancaketrade-558a540\.venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\HACKER\Desktop\beeb-pancaketrade-558a540\.venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\HACKER\Desktop\beeb-pancaketrade-558a540\.venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\HACKER\Desktop\beeb-pancaketrade-558a540\.venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\HACKER\Desktop\beeb-pancaketrade-558a540\pancaketrade\trade.py", line 28, in main
    config = read_config(config_file)
  File "C:\Users\HACKER\Desktop\beeb-pancaketrade-558a540\pancaketrade\utils\config.py", line 82, in read_config
    data = yamale.make_data(config_file_path)
  File "C:\Users\HACKER\Desktop\beeb-pancaketrade-558a540\.venv\lib\site-packages\yamale\yamale.py", line 29, in make_data
    raw_data = readers.parse_yaml(path, parser, content=content)
  File "C:\Users\HACKER\Desktop\beeb-pancaketrade-558a540\.venv\lib\site-packages\yamale\readers\yaml_reader.py", line 35, in parse_yaml
    return parse(f)
  File "C:\Users\HACKER\Desktop\beeb-pancaketrade-558a540\.venv\lib\site-packages\yamale\readers\yaml_reader.py", line 11, in _pyyaml
    return list(yaml.load_all(f, Loader=Loader))
  File "C:\Users\HACKER\Desktop\beeb-pancaketrade-558a540\.venv\lib\site-packages\yaml\__init__.py", line 130, in load_all
    yield loader.get_data()
  File "C:\Users\HACKER\Desktop\beeb-pancaketrade-558a540\.venv\lib\site-packages\yaml\constructor.py", line 45, in get_data
    return self.construct_document(self.get_node())
  File "yaml\_yaml.pyx", line 699, in yaml._yaml.CParser.get_node
  File "yaml\_yaml.pyx", line 725, in yaml._yaml.CParser._compose_document
  File "yaml\_yaml.pyx", line 776, in yaml._yaml.CParser._compose_node
  File "yaml\_yaml.pyx", line 892, in yaml._yaml.CParser._compose_mapping_node
  File "yaml\_yaml.pyx", line 905, in yaml._yaml.CParser._parse_next_event
yaml.scanner.ScannerError: while scanning a simple key
  in "user_data\config.yml", line 6, column 1
could not find expected ':'
  in "user_data\config.yml", line 7, column 17

Can you clarify what's this???
![image](https://user-images.githubusercontent.com/56129687/141677903-0a5248d7-157f-4169-92fa-fd9d09148890.png)

**Comment by beeb** [comment]
Did you follow all instructions in the Readme, installed the required packages with `poetry install` and wrote your config file? what is the content of your config file? do no publish any sensitive information of course.

**Comment by DjdjHacks** [comment]
> Did you follow all instructions in the Readme, installed the required packages with `poetry install` and wrote your config file? what is the content of your config file? do no publish any sensitive information of course.
[config.txt](https://github.com/beeb/pancaketrade/files/7533599/config.txt)

**Comment by beeb** [comment]
Thanks. The file should be named `config.yml` as explained in the docs.
I don't know if you have any information on line 6 next to `secrets:` but that line should be empty afterwards.

**Comment by DjdjHacks** [comment]
This is the config '*' denotes my data and i've uploaded it in txt cuz yml is not supported.

**Comment by DjdjHacks** [comment]
I'm an idiot. Sorry for wasting your time

**Comment by DjdjHacks** [comment]
Thanks for that fast reply, I thought the space next to secrets: is where my private keys goes. 
Again , I didn't expected that fast reply. Thanks.

BTW do you cut any charges in the program?

**Comment by beeb** [comment]
Ok good to know nothing was wrong. There are no dev fees in the program, it's completely free to use, as stated in the license. You can check the source for yourself as it is open source.

Best of luck
