### ISSUE TITLE
ConnectTimeoutError, NewConnectionError, Network.update_nonce

### ISSUE THREAD

**Issue by jazzlifepro** [beeb/pancaketrade#93]
Hello king! I hope you are doing very well!
sorry for the inconvenience. i have a little error

WARNING |Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x>, 'Connect timed out. (connect timeout=5.0)')': /bot/setMyCommands

WARNING |Execution of job "Network.update_nonce (trigger: interval[0:00:10], next run at: 2022-08-31 12:16:23 -03)" skipped: maximum number of running instances reached (1)
WARNING |Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x>: Failed to establish a new connection: [Errno -2] Name or service not known')': /bot/getUpdates
WARNING |Execution of job "Network.update_nonce (trigger: interval[0:00:10], next run at: 2022-08-31 12:16:33 -03)" skipped: maximum number of running instances reached (1)
WARNING |Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x>: Failed to establish a new connection: [Errno -2] Name or service not known')': /
WARNING |Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x>: Failed to establish a new connection: [Errno -2] Name or service not known')': /bot/getUpdates
WARNING |Execution of job "Network.update_nonce (trigger: interval[0:00:10], next run at: 2022-08-31 12:16:43 -03)" skipped: maximum number of running instances reached (1)
WARNING |Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x>: Failed to establish a new connection: [Errno -2] Name or service not known')': /bot/getUpdates

why tell me this ?

**Comment by beeb** [comment]
Hey there. This looks more like a network issue on your side, or a configuration problem with the telegram bot token. I don't see how I can help here.

**Comment by jazzlifepro** [comment]
I dont have problem with internet connection.
Now it gives me this error:
ERROR  |An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/home/morpheus/pancaketrade/.venv/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 536, in process_update
    self.dispatch_error(None, update)
  File "/home/morpheus/pancaketrade/.venv/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 810, in dispatch_error
    callback(update, context)
  File "/home/morpheus/pancaketrade/pancaketrade/bot.py", line 400, in error_handler
    chat_message(update, context, text=f"⛔️ Exception while handling an update\n{context.error}", edit=False)
  File "/home/morpheus/pancaketrade/pancaketrade/utils/generic.py", line 81, in chat_message
    assert update.effective_chat
AttributeError: 'NoneType' object has no attribute 'effective_chat'

I get the feeling that it is a problem with python3.8

**Comment by jazzlifepro** [comment]
I had trouble installing docker so I reinstalled with poetry, loaded other different tokens and so far no issues. 
thanks for the patience!
